config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :api, defaults: { format: 'json' } do
    resources :addons, only: [:index]
    match 'checkouts/:id/single' => 'checkouts#spc_update', via: [:put]
    match 'checkouts/:id/purchase' => 'checkouts#spc_purchase', via: [:put]
    match 'checkouts/:id/shipments' => 'checkouts#spc_update_shipments', via: [:put]
  end
  namespace :admin do
    match 'addons/edit', to: 'addon_configuration#edit', via: [:get]
    match 'addons', to: 'addon_configuration#update', via: [:patch, :put]
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  # checkout_flow do
  #   go_to_state :address
  #   go_to_state :review
  #   go_to_state :complete
  # end
end

app/models/spree/shipping_rate_decorator.rb
Spree::ShippingRate.class_eval do
  belongs_to :shipment, class_name: 'Spree::Shipment', touch: true
end

app/controllers/spree/admin/addon_configuration_controller.rb
module Spree
  module Admin
    class AddonConfigurationController < Spree::Admin::BaseController
      def edit
        @addons = get_addons
      end

      def update
        variant_ids = addon_params['variants'].collect(&:to_i)
        set_addons(variant_ids)
        @addons = get_addons
        respond_to do |format|
          format.js { render :update }
        end
      end

      private

      def addon_params
        params.require(:addon).permit(:variants => [])
      end

      def configuration
        Spree::SinglePageCheckout::AddonConfiguration.new
      end

      def get_addons
        Spree::Variant.where(id: configuration.preferred_addon_variants)
      end

      def set_addons(variants)
        configuration.preferred_addon_variants = variants
      end
    end
  end
end

app/controllers/spree/api/addons_controller.rb
module Spree
  module Api
    class AddonsController < Spree::Api::BaseController
      skip_filter :authenticate_user, :load_user

      def index
        # re-implement this with your own in a decorator; this placeholder
        # should allow the basic implementation to stand
        @addons = Kaminari.paginate_array(addon_variants).page(params[:page]).per(params[:per_page])
        respond_with(@addons)
      end

      private

      def addon_variants
        configuration = Spree::SinglePageCheckout::AddonConfiguration.new
        Spree::Variant.where(id: configuration.preferred_addon_variants)
      end
    end
  end
end

app/controllers/spree/api/checkouts_controller_decorator.rb
Spree::Api::CheckoutsController.class_eval do
  def spc_update
    spc_load_order
    authorize! :update, @order, order_token
    @order.payments.destroy_all if @order.payments.any?

    if @order.update_from_params(params, permitted_checkout_attributes, request.headers.env)

      # Add the coupon code if present and one hasn't already been applied
          binding.pry
      if @order.can_add_coupon? && nested_params[:coupon_code]
        handler = Spree::PromotionHandler::Coupon.new(@order).apply
        if handler.error.present?
          spc_errors[:coupon] = handler.error
        end
      end

      # Hackish way of getting fresh info
      @order.update(state: :address)
      2.times { @order.next }

      respond_with(@order, default_template: 'spree/api/orders/show_with_manifest', status: 200)
    else
      invalid_resource! @order
    end
  end

  def spc_purchase
    spc_load_order
    authorize! :update, @order, order_token

    while @order.next; end
    respond_with(@order, default_template: 'spree/api/orders/show_with_manifest', status: 200)
  end

  def spc_update_shipments
    spc_load_order
    authorize! :update, @order, order_token

    @shipment = Spree::Shipment.find(params[:checkout][:id])
    @shipment.selected_shipping_rate_id = params[:checkout][:selected_shipping_rate_id]

    updater = Spree::OrderUpdater.new(@order)
    updater.update_shipments

    @order.reload
    respond_with(@order, default_template: 'spree/api/orders/show_with_manifest', status: 200)
  end

  private

  def spc_errors
    @spc_errors ||= {}
  end

  def spc_load_order
    @order = Spree::Order.eager_load(
      :payments,
      :bill_address,
      :ship_address,
      shipments: [
        :shipping_methods,
        :shipping_rates,
      ],
      line_items: [
        variant: [
          :images,
          :stock_items
        ]
      ]
    ).find_by(number: params[:id])
    raise_insufficient_quantity and return if @order.insufficient_stock_lines.present?
  end
end

app/controllers/spree/api/line_items_controller_decorator.rb
Spree::Api::LineItemsController.class_eval do
  private

  # override this method to use a line_item's variant_id as well during lookup
  #  - Allows for kinda crappy javascript, but prevents complex refactoring ATM
  #  - TODO:  Clean up the JS and remove this override
  def find_line_item
    id = params[:id].to_i
    order.line_items.detect { |line_item|
      line_item.id == id || line_item.variant_id == id
    } or raise ActiveRecord::RecordNotFound
  end
end

app/views/spree/admin/addon_configuration/_add_variant.html.erb
<%= javascript_include_tag 'spree/backend/variant_autocomplete' %>
<%= render partial: 'spree/admin/variants/autocomplete', formats: [:js] %>
<%= render partial: 'addon_config', formats: [:js] %>

<div id="add-addon-pref" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:add_variant_to_addons) %></legend>

    <div data-hook="add_variant_name" class="field twelve columns alpha">
      <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_variant_id, "", class: 'variant-autocomplete fullwidth' %>
    </div>

    <%= content_tag 'div', id: 'addon-update-form' do %>
      <%= render 'form' %>
    <% end %>

  </fieldset>
</div>

app/views/spree/admin/addon_configuration/_addon_config.js.erb
<script>
$(document).ready(function() {
  'use strict';

  $('[data-hook="add_variant_name"]').find('.variant-autocomplete').variantAutocomplete();

  $('#add_variant_id').on('change', function() {
    var variantId = $('#add_variant_id').val();

    if (variantId) {
      $('#new-addon-field').val(variantId);
    }
  });

  $('#addons').on('click', '.remove-addon', function(e) {
    e.preventDefault();
    var variantId = $(this).attr('data-variant-id');

    $('#variant-' + variantId).remove();
    $('#addon-update-form form').submit();
  });
});
</script>

app/views/spree/admin/addon_configuration/_addons.html.erb
<table class="addons index table" data-hook="addons">
  <colgroup>
    <col style="width: 10%;" />
    <col style="width: 75%;" />
    <col style="width: 15%;" />
  </colgroup>

  <thead>
    <th colspan="2"><%= Spree.t(:name) %></th>
    <th class="actions">&nbsp;</th>
  </thead>

  <tbody>
    <% @addons.each do |addon| %>
      <tr class="variant">
        <td class="variant-image">
          <%= mini_image(addon) %>
        </td>
        <td class="variant-name">
          <%= addon.product.name %>
        </td>
        <td class="variant-actions text-right">
          <%= link_to '#', class: 'remove-addon btn btn-danger btn-sm no-text with-tip', title: 'Remove from addons', :'data-variant-id' => addon.id do %>
            <span class="icon icon-delete"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/addon_configuration/_form.html.erb
<%= form_tag admin_addons_path, method: :put, remote: true, class: 'text-right' do %>
  <% @addons.each do |variant| %>
    <%= hidden_field_tag 'addon[variants][]', variant.id, id: "variant-#{variant.id}" %>
  <% end %>
  <%= hidden_field_tag 'addon[variants][]', nil, id: 'new-addon-field' %>
  <%= button_tag type: 'submit', class: 'btn btn-sm btn-success' do %>
    <i class="icon icon-plus"></i> Add to Addons
  <% end %>
<% end %>

app/views/spree/admin/addon_configuration/edit.html.erb
<%#= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:addon_configuration) %>
<% end %>

<%= render 'add_variant' %>

<fieldset class="no-border-bottom">
  <legend align="center"><%= Spree.t(:current_addon_items) %></legend>
</fieldset>

<div id="addons">
  <%= render 'addons' %>
</div>

app/views/spree/admin/addon_configuration/update.js.erb
$('#addons').html('<%= render('addons').squish.html_safe %>');
$('#addon-update-form').html('<%= render('form').squish.html_safe %>');

app/views/spree/checkout/_single_page_checkout.html.erb
<% @page_title = 'REVIEW YOUR ORDER' %>

<%= content_for :head do %>
  <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=false' %>
<% end %>

<div class="row checkout-container" id="checkout-content" data-hook>
  <div class="col-xs-12 col-sm-5 col-md-5">
    <div class="checkout-container index">

      <%# Shipping Address Form %>
      <div class="addressInfo info" id="spc-shipping-address">
        <h3>Shipping Address</h3>
        <%= render partial: 'spree/checkout/single_page_checkout/address_form',
            locals: { address: @order.shipping_address, geolocate: true } %>
        <div class="spc-billing-toggle-container">
          <%= check_box_tag 'billing', 'yes', true, class: 'billing-address-toggle' %>
          <%= label_tag 'billing' do %>
            <span class='fa fa-check-square-o'></span>
            Use Same Address For Billing
          <% end %>
        </div>
      </div>

      <%# Billing Address Form %>
      <div class="addressInfo info" id="spc-billing-address">
        <h3>Billing Address</h3>
        <%= render partial: 'spree/checkout/single_page_checkout/address_form',
            locals: { address: @order.billing_address, geolocate: false } %>
      </div>

      <%# Payment Information %>
      <%= render 'spree/checkout/single_page_checkout/payment_form' %>
    </div>
  </div>

  <%# Order Summary - Displays to right of address & payment info & is updated via AJAX %>
  <div class="col-xs-12 col-sm-7 col-md-7">

    <%# Pay button container required for the shake effect %>
    <div id="pay-button-container">
      <button class="btn checkout-btn btn-lg btn-primary btn-block" id="checkout-pay-btn">
        <%# Default "Pay $0.00" text %>
        <span class="spc-button-text">Pay&nbsp;<span class="spc-button-text checkout-total" id="button-price"><%= number_to_currency( @order.total ) %></span></span>
        <%# Displays when form is invalid %>
        <span class="spc-need-info">Missing required info</span>
        <%# Displays when order is ready to be placed %>
        <span class="spc-place-order">PLACE ORDER</span>
        <span class="spc-order-processing">Processing your order</span>
      </button>
    </div>

    <div class="panel-box" id="spc-checkout-summary">
      <div id="line-items">
      <% @order.line_items.each do |item| %>
        <div class="row">
          <div class="col-xs-2 col-sm-2 col-md-2">
            <%= small_image(item.variant) %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-2 col-sm-1 col-md-1">
            <%= item.quantity %>
          </div>
          <div class="col-xs-10 col-sm-8 col-md-8">
            <%= item.name %>
          </div>
          <div class="col-xs-12 col-sm-3 col-md-3 right-text">
            <%= number_to_currency( item.price ) %>
          </div>
        </div>
      <% end %>
      </div>


      <%# Addon items. Elements inside are generated via the JS file. %>
      <div class="checkout-addons-header row">
      </div>
      <div class="checkout-addons row">
      </div>


      <%# Price adjustments / promotions %>
      <%# For line-item promotions %>
      <div id="line-item-adjustments">
      <% if @order.line_item_adjustments.exists? %>
        <% @order.line_item_adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <div class="checkbox-box promotion-label">
              <%= label %> &nbsp;
              <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>
          </div>
        <% end %>
      <% end %>
      </div>
      <%# For promotions on the whole order %>
      <div id="order-adjustments">
        <% if @order.adjustments.exists? %>
          <% @order.adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <div class="checkbox-box promotion-label">
                <%= label %> &nbsp;
                <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>
            </div>
          <% end %>
        <% end %>
      </div>

      <%# Tax %>
      <div id="taxes">
      <% @order.all_adjustments.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <div class="checkbox-box">
          <%= label %> &nbsp;
          (+ <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>)
        </div>
      <% end %>
      </div>

      <%# Order Total %>
      <div class="row total">
        <div class="col-xs-6 col-sm-9 col-md-9">Total</div>
        <div class="col-xs-6 col-sm-3 col-md-3 right-text checkout-total"><%= number_to_currency( @order.total ) %></div>
      </div>


    </div>
  </div>
</div>

<%# Mustache Template to fill in line_items into shipments after first load %>
<script id="checkout-shipment-template" type="text/x-handlebars-template">
  Shipment #{{number}}
  {{#each shipment.manifest}}
    <div class="row">
      <div class="col-xs-2 col-sm-2 col-md-2">
        <img src="{{variant.images.[0].mini_url}}" alt="{{variant.name}}"></img>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 col-sm-1 col-md-1">
        {{quantity}}
      </div>
      <div class="col-xs-10 col-sm-8 col-md-8">
        {{variant.name}}
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3 right-text">
        ${{display_amount}}
      </div>
    </div>
  {{/each}}
  <div class="checkout-shipping row">
    <p>Shipping: </p>
    {{#each shipment.shipping_rates}}
      <div class="checkbox">
        <input type="radio" name="checkout_shipping" shipment="{{../shipment.id}}"
          val="{{id}}" id="checkout_shipping{{id}}" />
        <label for="checkout_shipping{{id}}">
        {{#ifEql ../shipment.selected_shipping_rate.id this.id}}
          <i class="fa fa-check-square-o"></i>
        {{else}}
          <i class="fa fa-square-o"></i>
        {{/ifEql}}
          {{name}} &nbsp; ( +{{display_cost}} )
        </label>
      </div>
    {{/each}}
  </div>

  <hr />
</script>

app/views/spree/checkout/single_page_checkout/_address_form.erb
<%= form_for address, url: spree.api_order_path(@order), html: { autocomplete: 'on' } do |form|%>
  <div class="row top-row">
    <%= form.text_field(:full_name,
      required: true,
      id: "#{ address.id }-full-name",
      class: 'form-control name',
      placeholder: 'Name',
      autocomplete: 'name'
    ) %>
  </div>
  <div class="row middle-row">
    <div class="col-md-12">
      <%= form.collection_select(:country_id,
        available_countries,
        :id,
        :name,
        { include_blank: true },
        {
          id: "#{ address.id }-country-id",
          class: 'form-control country',
          required: true,
          autocomplete: 'country-name'
        }
      ) %>
    </div>
  </div>
    <div class="row middle-row">
      <% if geolocate %>
        <div class="col-xs-10 noPadding">
          <%= form.text_field(:address1,
            required: true,
            id: "#{ address.id }-address1",
            class: 'form-control street',
            placeholder: 'Address',
            autocomplete: 'address-line1'
          ) %>
        </div>
        <div class="col-xs-2 noPadding geoLocator right-col">
          <i class="fa fa-crosshairs"></i>
        </div>
      <% else %>
        <div class="col-md-12">
          <%= form.text_field(:address1,
            required: true,
            id: "#{ address.id }-address1",
            class: 'form-control street',
            placeholder: 'Address',
            autocomplete: 'address-line1'
          ) %>
        </div>
      <% end %>
    </div>
  <div class="row middle-row">
    <div class="col-xs-12 col-sm-6 col-md-6">
      <%= form.text_field(:address2,
        id: "#{ address.id }-address2",
        class: 'form-control apt',
        placeholder: 'Address 2',
        autocomplete: 'address-line2'
      ) %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 right-col">
      <%= form.text_field(:city,
        required: true,
        id: "#{ address.id }-city",
        class: 'form-control city',
        placeholder: 'City',
        autocomplete: 'address-level2'
      ) %>
    </div>
  </div> <%# .row %>
  <div class="row middle-row">
    <div class="col-xs-12 col-sm-8 col-md-8 states-container">
      <% if form.object.state_name.present? %>
        <%= form.text_field(:state_name,
          id: "#{ address.id }-address_state_name",
          class: 'form-control state',
          placeholder: 'State, Province, or Region',
          autocomplete: 'address-level1'
        )%>
      <% else %>
        <% state_name = form.object.state ? form.object.state.name : nil %>
        <%= form.collection_select(:state_name,
          form.object.country.states.sort,
          :name,
          :name,
          {
            selected: state_name,
            include_blank: true
          },
          {
            id: "#{ address.id }-state-name",
            class: 'form-control state',
            required: true,
            autocomplete: 'address-level1',
            placeholder: 'State'
          }
        ) %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 right-col">
      <%= form.text_field(:zipcode,
        required: true,
        id: "#{ address.id }-zipcode",
        class: 'form-control zipcode',
        placeholder: 'Zip',
        autocomplete: 'postal-code'
      ) %>
    </div>
  </div>
  <div class="row bottom-row">
    <div class="col-md-12">
      <%= form.phone_field(:phone,
        required: true,
        id: "#{ address.id }-phone",
        class: 'form-control phone',
        placeholder: 'Phone',
        autocomplete: 'tel-national'
      ) %>
    </div>
  </div>
<% end %>

app/views/spree/checkout/single_page_checkout/_button.html.erb
<button type="button" id="<%= id %>" class="spc-ripple-btn <%= klass %>">
  <span class="spc-ripple-btn-contents">
    <%= content %>
  </span>
</button>

app/views/spree/checkout/single_page_checkout/_pay_button.html.erb
<%# Pay button container required for the shake effect %>
<div id="pay-button-container">
  <button class="btn checkout-btn btn-lg btn-primary btn-block" id="checkout-pay-btn">
    <%# Default "Pay $0.00" text %>
    <span class="spc-button-text">
      Pay&nbsp;
      <span class="spc-button-text checkout-total" id="button-price">
        <%= number_to_currency( @order.total ) %>
      </span>
    </span>
    <%# Displays when form is invalid %>
    <span class="spc-need-info">Missing required info</span>
    <%# Displays when order is ready to be placed %>
    <span class="spc-place-order">PLACE ORDER</span>
    <span class="spc-order-processing">Processing your order</span>
  </button>
</div>

app/views/spree/checkout/single_page_checkout/_payment_form.erb
<h3>Payment Information</h3>
<div class="paymentInfo info">
  <%= form_tag update_checkout_path(state: 'payment'), { autocomplete: 'on', method: 'patch', id: 'payment-form' } do %>
    <%= hidden_field_tag 'action', 'update' %>
    <%= hidden_field_tag 'state', 'payment' %>

    <div class="row top-row">
      <%= hidden_field_tag 'order[payments_attributes][][payment_method_id]',
        @order.available_payment_methods.first.id,
        id: 'payment_method_id' %>
      <%= text_field_tag(
        "payment_source[#{ @order.available_payment_methods.first.id }][name]",
        "#{ session[:payment_details] ? session[:payment_details][:name] : nil }",
        {
          id: 'name',
          class: 'form-control paymentName',
          autocomplete: 'cc-name',
          placeholder: 'Cardholder Name',
          required: true
        }
      ) %>
    </div>

    <div class="row middle-row">
      <div class="col-md-12">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-fw fa-credit-card"></i></span>
          <%= text_field_tag(
            "payment_source[#{ @order.available_payment_methods.first.id }][number]",
            "#{ session[:payment_details] ? session[:payment_details][:number] : nil }",
            {
              id: 'number',
              class: 'form-control',
              autocomplete: 'cc-number',
              placeholder: 'Card Number',
              pattern: '\d*',
              required: true
            }
          ) %>
          <%= hidden_field_tag(
            "payment_source[#{ @order.available_payment_methods.first.id }][cc_type]",
            nil,
            { id: 'cc-type' }
          ) %>
        </div>
      </div>
    </div>

    <div class="row middle-row">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="input-group date">
          <span class="input-group-addon"><i class="fa fa-fw fa-calendar-o"></i></span>
          <%= text_field_tag(
            "payment_source[#{ @order.available_payment_methods.first.id }][expiry]",
            "#{ session[:payment_details] ? session[:payment_details][:expiry] : nil }",
            {
              autocomplete: 'cc-exp',
              class: 'form-control date',
              id: 'date',
              pattern: '\d*',
              placeholder: 'MM / YY',
              required: true
            }
          ) %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-6 right-col">
        <div class="input-group code">
          <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
          <%= text_field_tag(
            "payment_source[#{ @order.available_payment_methods.first.id }][verification_value]",
            nil,
            {
              autocomplete: 'cc-csc',
              class: 'form-control code',
              id: 'verification_value',
              pattern: '\d*',
              placeholder: 'CVC',
              required: true
            }
          ) %>
        </div>
      </div>
    </div>
  <% end # Form Tag %>

  <%# Coupon Code Input -- Submitted async. %>
    <div class="row bottom-row">
      <div class="input-group">
        <%= text_field_tag(
          'order[coupon_code]',
          nil,
          {
            class: 'form-control coupon',
            id: 'coupon_code',
            placeholder: 'Promotion Code'
          }
        ) %>
        <span class="input-group-btn">
          <button class="btn btn-default spc-promo-btn" id="spc-promo-apply" type="button">Apply</button>
        </span>
      </div>
    </div>
  <% session[:payment_details] = nil %>
</div>

app/views/spree/checkout/single_page_checkout/_summary.html.erb
<div class="panel-box" id="spc-checkout-summary">
  <div id="line-items">
    <% @order.line_items.each do |item| %>
      <div class="row">
        <div class="col-xs-2 col-sm-2 col-md-2">
          <%= small_image(item.variant) %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-2 col-sm-1 col-md-1">
          <%= item.quantity %>
        </div>
        <div class="col-xs-10 col-sm-8 col-md-8">
          <%= item.name %>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-3 right-text">
          <%= number_to_currency( item.price ) %>
        </div>
      </div>
    <% end %>
  </div>


  <%# Addon items. Elements inside are generated via the JS file. %>
  <div class="checkout-addons-header row"></div>
  <div class="checkout-addons row"></div>


  <%# Price adjustments / promotions %>
  <%# For line-item promotions %>
  <div id="line-item-adjustments">
    <% if @order.line_item_adjustments.exists? %>
      <% @order.line_item_adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
        <div class="checkbox-box promotion-label">
          <%= label %> &nbsp;
          <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%# For promotions on the whole order %>
  <div id="order-adjustments">
    <% if @order.adjustments.exists? %>
      <% @order.adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
        <div class="checkbox-box promotion-label">
          <%= label %> &nbsp;
          <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%# Tax %>
  <div id="taxes">
    <% @order.all_adjustments.tax.eligible.group_by(&:label).each do |label, adjustments| %>
      <div class="checkbox-box">
        <%= label %> &nbsp;
        (+ <%= Spree::Money.new(adjustments.sum(&:amount)).to_html %>)
      </div>
    <% end %>
  </div>

  <%# Order Total %>
  <div class="row total">
    <div class="col-xs-6 col-sm-9 col-md-9">Total</div>
    <div class="col-xs-6 col-sm-3 col-md-3 right-text checkout-total">
      <%= number_to_currency( @order.total ) %>
    </div>
  </div>

</div>